#!/usr/bin/env bash
# Regenerate the Homebrew formula for a Dragon Code release.
# Usage: gen-formula.sh <version> <dist_repo> <out_file>
# Downloads the release assets, computes sha256, renders Formula/dragon.rb.
set -euo pipefail

VERSION="${1:?version required, no leading v}"
DIST_REPO="${2:-VELLORAAI/dragoncode-public-dist}"
OUT="${3:?output path required}"

BASE="https://github.com/${DIST_REPO}/releases/download/v${VERSION}"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

sha() {
  local asset="$1"
  curl -fsSL "${BASE}/${asset}" -o "${tmp}/${asset}"
  # shasum is present on macOS + Linux (perl core); sha256sum is Linux-only.
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "${tmp}/${asset}" | awk '{print $1}';
  else shasum -a 256 "${tmp}/${asset}" | awk '{print $1}'; fi
}

DARWIN_ARM64="$(sha "dragon-darwin-arm64.zip")"
LINUX_ARM64="$(sha "dragon-linux-arm64.tar.gz")"
LINUX_X64="$(sha "dragon-linux-x64.tar.gz")"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by the dragon-release workflow. Do not edit by hand.
class Dragon < Formula
  desc "AI coding agent — thin client for the Dragon Code gateway"
  homepage "https://github.com/${DIST_REPO}"
  version "${VERSION}"
  license :cannot_represent

  on_macos do
    on_arm do
      url "${BASE}/dragon-darwin-arm64.zip"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      odie "Dragon Code has no native Intel-Mac build. Use Apple Silicon, or the curl installer: https://github.com/${DIST_REPO}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/dragon-linux-arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "${BASE}/dragon-linux-x64.tar.gz"
      sha256 "${LINUX_X64}"
    end
  end

  def install
    bin.install "dragon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dragon --version")
  end
end
EOF

echo "wrote $OUT (darwin-arm64=$DARWIN_ARM64 linux-arm64=$LINUX_ARM64 linux-x64=$LINUX_X64)"
