#!/usr/bin/env bash
# Regenerate the Homebrew formula for a Dragon Code release.
# Usage: gen-formula.sh <version> <dist_repo> <out_file>
# Downloads the release assets, computes sha256, renders Formula/dragon.rb, and
# embeds the bundled man page (dragon.1 at the repo root) so `man dragon` works
# after `brew install`.
set -euo pipefail

VERSION="${1:?version required, no leading v}"
DIST_REPO="${2:-VELLORAAI/dragoncode-public-dist}"
OUT="${3:?output path required}"
# dragon.1 lives at the tap repo root (two levels up from .github/scripts).
MAN_SRC="${MAN_SRC:-$(cd "$(dirname "$0")/../.." && pwd)/dragon.1}"

BASE="https://github.com/${DIST_REPO}/releases/download/v${VERSION}"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

sha() {
  local asset="$1"
  curl -fsSL "${BASE}/${asset}" -o "${tmp}/${asset}"
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "${tmp}/${asset}" | awk '{print $1}';
  else shasum -a 256 "${tmp}/${asset}" | awk '{print $1}'; fi
}

# sha of an OPTIONAL asset: empty (not a hard error) when the asset is absent,
# so the generator self-heals — it emits a real Intel-Mac build once
# dragon-darwin-x64.zip is published, and keeps the odie fallback before then.
sha_optional() {
  local asset="$1"
  if curl -fsSL "${BASE}/${asset}" -o "${tmp}/${asset}" 2>/dev/null; then
    if command -v sha256sum >/dev/null 2>&1; then sha256sum "${tmp}/${asset}" | awk '{print $1}';
    else shasum -a 256 "${tmp}/${asset}" | awk '{print $1}'; fi
  fi
}

DARWIN_ARM64="$(sha "dragon-darwin-arm64.zip")"
DARWIN_X64="$(sha_optional "dragon-darwin-x64.zip")"
LINUX_ARM64="$(sha "dragon-linux-arm64.tar.gz")"
LINUX_X64="$(sha "dragon-linux-x64.tar.gz")"

# Intel-Mac block: a real url/sha once the asset exists, else the odie fallback.
if [ -n "$DARWIN_X64" ]; then
  MAC_INTEL="    on_intel do
      url \"${BASE}/dragon-darwin-x64.zip\"
      sha256 \"${DARWIN_X64}\"
    end"
else
  MAC_INTEL="    on_intel do
      odie \"Dragon Code has no native Intel-Mac build for this release yet. Use Apple Silicon, or the curl installer: https://github.com/${DIST_REPO}\"
    end"
fi

mkdir -p "$(dirname "$OUT")"

# Head: metadata + platform blocks, through `bin.install`.
cat > "$OUT" <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by the update-formula workflow. Do not edit by hand.
class Dragon < Formula
  desc "AI coding agent — thin client for the Dragon Code gateway"
  homepage "https://github.com/${DIST_REPO}"
  version "${VERSION}"
  license :cannot_represent

  on_macos do
    on_arm do
      url "${BASE}/dragon-darwin-arm64.zip"
      sha256 "${DARWIN_ARM64}"
    end
${MAC_INTEL}
  end

  on_linux do
    on_arm do
      url "${BASE}/dragon-linux-arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "${BASE}/dragon-linux-x64.tar.gz"
      sha256 "${LINUX_X64}"
    end
  end

  def install
    bin.install "dragon"
EOF

# Man page: embed dragon.1 verbatim (literal cat between quoted heredoc markers
# so roff escapes survive), then install it.
if [ -f "$MAN_SRC" ]; then
  {
    echo "    (buildpath/\"dragon.1\").write(<<'DRAGON_MANPAGE')"
    cat "$MAN_SRC"
    echo "DRAGON_MANPAGE"
    echo '    man1.install "dragon.1"'
  } >> "$OUT"
fi

# Tail: test block + end.
cat >> "$OUT" <<EOF
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dragon --version")
  end
end
EOF

echo "wrote $OUT (darwin-arm64=$DARWIN_ARM64 darwin-x64=${DARWIN_X64:-<none>} linux-arm64=$LINUX_ARM64 linux-x64=$LINUX_X64; man=$( [ -f "$MAN_SRC" ] && echo yes || echo MISSING ))"
