# typed: false
# frozen_string_literal: true

# This file is generated by the update-formula workflow. Do not edit by hand.
class Dragon < Formula
  desc "AI coding agent — thin client for the Dragon Code gateway"
  homepage "https://github.com/VELLORAAI/dragoncode-public-dist"
  version "1.4.43"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.4.43/dragon-darwin-arm64.zip"
      sha256 "e9b6df59f56908eec291a5708a417909f506938e85d3bb762476c7f8e769bcdf"
    end
    on_intel do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.4.43/dragon-darwin-x64.zip"
      sha256 "81bdea4f481b76b6d7c4e3fe3cd16e79d1ed904bd24c1072be156eccb5321b49"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.4.43/dragon-linux-arm64.tar.gz"
      sha256 "27fb5b2c3694ba904282b9902f18c96d029b351c12a633e255f9308da57526af"
    end
    on_intel do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.4.43/dragon-linux-x64.tar.gz"
      sha256 "03cd93fadb5dde003fe80d094186ecc31dddf06e09b3b22796c227438712dfbb"
    end
  end

  def install
    bin.install "dragon"
    (buildpath/"dragon.1").write(<<'DRAGON_MANPAGE')
.TH DRAGON 1 "July 2026" "Dragon Code" "User Commands"
.SH NAME
dragon \- Dragon Code, an AI coding agent for the terminal
.SH SYNOPSIS
.B dragon
.RI [ project ]
.RI [ options ]
.br
.B dragon
.I command
.RI [ args ]
.RI [ options ]
.SH DESCRIPTION
.B dragon
is the Dragon Code terminal coding agent. Run with no command it opens an
interactive TUI in the given project directory (default: the current
directory). It defaults to the Dragon lane (Kimi K2.7\-Code, served through the
Dragon gateway at api.mws.run), automatically indexes the repository for
whole\-codebase retrieval, and ships with native built\-in skills.
.PP
On first run, paste your Dragon API key when prompted, or set
.B DRAGON_API_KEY
in the environment.
.SH COMMANDS
.TP
.B run " [message..]"
Run a single turn non\-interactively with the given message; prints the result
and exits. Honors \fB\-\-model\fR, \fB\-\-agent\fR, \fB\-\-continue\fR, \fB\-\-session\fR.
.TP
.B serve
Start a headless Dragon server (HTTP API). See \fB\-\-port\fR, \fB\-\-hostname\fR.
.TP
.B web
Start the server and open the web interface.
.TP
.B attach " <url>"
Attach to an already\-running Dragon server.
.TP
.B skills " (alias: skill)"
Manage agent skills via the skills.sh ecosystem:
.BR "skills add " <source>,
.BR "skills update " "[names]," " skills list" ", " check ", " remove ", " find.
Installed skills auto\-update at startup (see \fBskills_autoupdate\fR).
.TP
.B mcp
Manage MCP (Model Context Protocol) servers.
.TP
.B providers " (alias: auth)"
Manage AI providers and credentials.
.TP
.B agent
Manage agents.
.TP
.B models " [provider]"
List available models.
.TP
.B session
Manage sessions.
.TP
.B export " [sessionID]"
Export session data as JSON.
.TP
.B import " <file>"
Import session data from a JSON file or URL.
.TP
.B stats
Show token usage and cost statistics.
.TP
.B index
Manage Dragon code indexing.
.TP
.B github
Manage the GitHub agent.
.TP
.B pr " <number>"
Fetch and check out a GitHub PR branch, then run Dragon.
.TP
.B plugin " <module> (alias: plug)"
Install a plugin and update config.
.TP
.B upgrade " [target]"
Upgrade Dragon Code to the latest or a specific version.
.TP
.B uninstall
Uninstall Dragon Code and remove related files.
.TP
.B acp
Start an ACP (Agent Client Protocol) server.
.TP
.B debug
Debugging and troubleshooting tools.
.TP
.B completion
Generate a shell completion script.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help.
.TP
.BR \-v ", " \-\-version
Show the version number.
.TP
.BR \-m ", " \-\-model " " \fIprovider/model\fR
Model to use (e.g. \fBdragon/dragon\fR, \fBdragon/max\fR).
.TP
.BR \-c ", " \-\-continue
Continue the last session.
.TP
.BR \-s ", " \-\-session " " \fIid\fR
Continue a specific session id.
.TP
.B \-\-fork
Fork the session when continuing (with \fB\-\-continue\fR or \fB\-\-session\fR).
.TP
.B \-\-agent " " \fIname\fR
Agent to use.
.TP
.B \-\-prompt " " \fItext\fR
Prompt to use.
.TP
.B \-\-mini
Start the minimal interactive interface.
.TP
.B \-\-pure
Run without external plugins.
.TP
.BR \-\-port " " \fIn\fR ", " \-\-hostname " " \fIhost\fR ", " \-\-cors " " \fIdomain\fR
Server bind options (for \fBserve\fR / \fBweb\fR).
.TP
.B \-\-print\-logs
Print logs to stderr.
.TP
.B \-\-log\-level " " \fILEVEL\fR
Log level: DEBUG, INFO, WARN, ERROR.
.SH ENVIRONMENT
.TP
.B DRAGON_API_KEY
Dragon gateway API key (alternative to the stored credential).
.TP
.B DRAGON_BASE_URL
Override the gateway base URL (default https://api.mws.run/v1).
.TP
.B DRAGON_INDEX_DISABLE
Set to 1 to disable background code indexing.
.TP
.B DRAGON_SENTINEL_HEADERS
Set to 0 to disable the X\-Mithrandir\-* request headers.
.TP
.B OPENCODE_DISABLE_BUILTIN_SKILLS
Set to 1 to disable the native built\-in starter skills.
.TP
.B OPENCODE_DISABLE_SKILLS_AUTOUPDATE
Set to 1 to disable startup skill auto\-update.
.TP
.B OPENCODE_DISABLE_BACKGROUND_SUBAGENTS
Set to 1 to disable asynchronous background subagents (the agent swarm).
.TP
.B OPENCODE_DISABLE_AUTOUPDATE
Set to 1 to disable binary auto\-update.
.SH FILES
.TP
.I ~/.config/dragon-code/
Global configuration (\fBdragon-code.jsonc\fR or \fBopencode.json\fR). Keys include
\fBskills_autoupdate\fR and \fBskills_builtin\fR.
.TP
.I ~/.local/share/dragon-code/auth.json
Stored credentials.
.TP
.I ~/.cache/dragon-code/
Cache (indexing state, skill\-update stamp).
.TP
.I .opencode/
Per\-project configuration, skills, and plugins.
.TP
.I .agents/skills/, .claude/skills/
Project and user skill directories.
.SH EXAMPLES
.TP
Start the TUI in the current repo:
.B dragon
.TP
One\-shot run on a specific model:
.B dragon run \-m dragon/max "explain src/server.ts"
.TP
Add a skill from a docs site:
.B dragon skills add https://docs.stripe.com
.TP
Upgrade to the latest release:
.B dragon upgrade
.SH SEE ALSO
Project and installation: https://github.com/VELLORAAI/dragoncode-public-dist
.br
Homebrew: \fBbrew install velloraai/tap/dragon\fR
.SH AUTHORS
Vellora AI. Dragon Code is a fork of OpenCode.
DRAGON_MANPAGE
    man1.install "dragon.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dragon --version")
  end
end
