# typed: false
# frozen_string_literal: true

# This file is generated by the dragon-release workflow. Do not edit by hand.
class Dragon < Formula
  desc "AI coding agent — thin client for the Dragon Code gateway"
  homepage "https://github.com/VELLORAAI/dragoncode-public-dist"
  version "1.1.9"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.2.0/dragon-darwin-arm64.zip"
      sha256 "0b6c09760135180334afa18da6a514114ce2952d79cb5107ba0e2c16b1bd46ff"
    end
    on_intel do
      odie "Dragon Code has no native Intel-Mac build. Use Apple Silicon, or the curl installer: https://github.com/VELLORAAI/dragoncode-public-dist"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.2.0/dragon-linux-arm64.tar.gz"
      sha256 "d16e4fc9c4b6c0a86746370aadf5fb30fc46fc39324c357ac7bbc7e199f03b9a"
    end
    on_intel do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.2.0/dragon-linux-x64.tar.gz"
      sha256 "1a9efaec3d22d2355df29e4e4fff33e90347870aa3ccc470b2e1b6393e86b13b"
    end
  end

  def install
    bin.install "dragon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dragon --version")
  end
end
