# typed: false
# frozen_string_literal: true

# This file is generated by the dragon-release workflow. Do not edit by hand.
class Dragon < Formula
  desc "AI coding agent — thin client for the Dragon Code gateway"
  homepage "https://github.com/VELLORAAI/dragoncode-public-dist"
  version "1.3.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.3.0/dragon-darwin-arm64.zip"
      sha256 "6d05280d6673fb9f82507185d9bfa453a58653972335ec2471eb83e2cd7c005d"
    end
    on_intel do
      odie "Dragon Code has no native Intel-Mac build. Use Apple Silicon, or the curl installer: https://github.com/VELLORAAI/dragoncode-public-dist"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.3.0/dragon-linux-arm64.tar.gz"
      sha256 "5419592f967ae68b964904468d9e38bf7ae5a055879d482307d06d72b26ae10c"
    end
    on_intel do
      url "https://github.com/VELLORAAI/dragoncode-public-dist/releases/download/v1.3.0/dragon-linux-x64.tar.gz"
      sha256 "f5d2866cf51ea3ae0ceefea3d537619d67f78d349649c7a2a1075512ffa76d8d"
    end
  end

  def install
    bin.install "dragon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dragon --version")
  end
end
